# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Prework"
  url = "/prework"
  weight = 1
  
[[main]]
  name = "Logistics"
  url = "#logistics"
  weight = 2

[[main]]
  name = "Schedule"
  url = "#schedule"
  weight = 3
  identifier = "schedule"
  
[[main]]
  name = "Week 1"
  url = "/post/week-1"
  weight = 1
  parent = "schedule"
  
[[main]]
  name = "Week 2"
  url = "/post/week-2"
  weight = 2
  parent = "schedule"

[[main]]
  name = "Week 3"
  url = "/post/week-3"
  weight = 3
  parent = "schedule"
  
[[main]]
  name = "Week 4"
  url = "/post/week-4"
  weight = 4
  parent = "schedule"
  
[[main]]
  name = "Week 5"
  url = "/post/week-5"
  weight = 5
  parent = "schedule"
  
[[main]]
  name = "Week 6"
  url = "/post/week-6"
  weight = 6
  parent = "schedule"

[[main]]
  name = "Week 7"
  url = "/post/week-7"
  weight = 7
  parent = "schedule"
  
[[main]]
  name = "Week 8"
  url = "/post/week-8"
  weight = 8
  parent = "schedule"
  
[[main]]
  name = "Syllabus"
  url = "#syllabus"
  weight = 4
  
[[main]]
  name = "People"
  url = "#people"
  weight = 5

[[main]]
  name = "Resources"
  url = "courses/resources/"
  weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
